<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.6.0+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.type()

'torch.LongTensor'

In [5]:
scalar.ndim
# scala has zero or no dimension

0

In [6]:
scalar.item()
# only works with one-element tensors

7

In [7]:
type(scalar.item())
# returns a python type int

int

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [12]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [15]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
tensor.device

device(type='cpu')

In [20]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6198, 0.1387, 0.3899, 0.9711],
        [0.1318, 0.6564, 0.9933, 0.9724],
        [0.7960, 0.3711, 0.3164, 0.1640]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.2777, 0.6392, 0.8146, 0.2903, 0.3888, 0.8296, 0.2801, 0.4362,
          0.0227, 0.3309],
         [0.3541, 0.6494, 0.3979, 0.1706, 0.0223, 0.0279, 0.1995, 0.3307,
          0.3995, 0.4267],
         [0.6266, 0.0623, 0.3654, 0.4882, 0.9073, 0.4551, 0.1746, 0.1268,
          0.0582, 0.9620],
         [0.8394, 0.8170, 0.3762, 0.4928, 0.4426, 0.1598, 0.4549, 0.8459,
          0.4834, 0.8935],
         [0.0462, 0.7590, 0.4543, 0.1955, 0.7481, 0.0052, 0.3901, 0.2167,
          0.6759, 0.0458],
         [0.5906, 0.4850, 0.8274, 0.6888, 0.8311, 0.5097, 0.8798, 0.5480,
          0.5225, 0.9673],
         [0.8824, 0.1773, 0.4213, 0.7427, 0.3306, 0.0982, 0.0232, 0.6785,
          0.7948, 0.6559],
         [0.8747, 0.6672, 0.8605, 0.5833, 0.6597, 0.0780, 0.4966, 0.3487,
          0.5528, 0.2348],
         [0.0681, 0.4244, 0.7935, 0.6713, 0.9901, 0.8313, 0.9060, 0.3954,
          0.4025, 0.6548],
         [0.0071, 0.4886, 0.1372, 0.5653, 0.1769, 0.9607, 0.5336, 0.5806,
          0.9189,

In [24]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [27]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [30]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
** Notes: ** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensor not the right datatype
2. Tensor not the right shape
3. Tensor not on the right device

In [31]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [32]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data types, float32 or float16, etc
                               device=device, # what device is the tensor on, cpu or cuda
                               requires_grad=False # should track gradients
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [33]:
# dtype of a tensor is default to float32, even if we specified it to None
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.half)
# half is same as float16, and float_16 apparently takes other attributes like device from float_32
float_16_tensor, float_16_tensor.device, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16),
 device(type='cuda', index=0),
 torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting information from tensors
* `shape` what shape is the tensor (some operations require specific shape rule)
* `dtype` what data type are stored in the tensor
* `device` what device the tensor is on (usually GPU or CPU)


In [36]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find some details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2240, 0.0573, 0.0746, 0.0681],
        [0.9984, 0.4931, 0.0167, 0.1181],
        [0.6731, 0.9163, 0.7608, 0.7095]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

In [37]:
# create tensor and add numbers to elements
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [38]:
tensor + 10

tensor([11, 12, 13])

In [39]:
# multiply elements
tensor * 10

tensor([10, 20, 30])

In [40]:
# tensor doesn't change unless reassigned
tensor

tensor([1, 2, 3])

### Matrix multiplication (is all you need)
The most common operation in neural net and deep learning is `matrix multiplication`, aka matmul in PyTorch.

The two rules for mat mul is:
1) The **inner dimensions** must match
2) The resulting matrix has the **outer dimensions**

In [41]:
# element wise multi
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# when tensors are 1D, dot product works
torch.dot(tensor, tensor), torch.inner(tensor, tensor)

(tensor(14), tensor(14))

In [44]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

torch.matmul(a, b), torch.mm(a, b)

(tensor([[19, 22],
         [43, 50]]),
 tensor([[19, 22],
         [43, 50]]))

In [47]:
# unlike numpy, torch dot product only works with 1d tensor of same length, so
# this cell would fail

# torch.dot(a, b)

In [48]:
# the at @ symbol is an operator for matmul
tensor @ tensor

tensor(14)

In [49]:
# so is torch.mm
# BUT torch.mm only works with matrix, not vector or tensor

# torch.mm(tensor, tensor)


In [50]:
%%time

# mat mul with loops
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.83 ms, sys: 0 ns, total: 1.83 ms
Wall time: 1.6 ms


In [51]:
%%time

# mat mul with torch method, which is faster by 3 order of magnitude
torch.matmul(tensor, tensor)

CPU times: user 60 µs, sys: 12 µs, total: 72 µs
Wall time: 59.1 µs


tensor(14)

### The most common in deep learning: shape errors   
To fix tensor shape issue, we can manipulate the shape of tensor using transpose


In [52]:
# create two tensor
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [53]:
# use T, or transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [54]:
# with b transposed, now the rule for mat mul is met
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum and other tensor aggregation.

In [55]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
# find avg

# watch out for dtype error for the dtype error
#torch.mean(x), x.mean()


In [59]:
# Need to specify data type from int/long to some float so we can do mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [60]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding position min and max, aka argmin and argmax

In [61]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
# argmin
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [63]:
# argmax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [64]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

* **Reshaping** - change shape of input tensor to a defined shape. _Total element counts need to be the same before and after._
* **View** - Return a view of an input tensor of certain shape but keep the same memory as original tensor, i.e, value changes in one will be visible to the other
* **Stacking** - combine multiple tensors on top of each other `vstack` or side by side `hstack`
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a tensor
* **Permute** - return a *view* of input with dimension order swapped in certain way

In [65]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
# add an extra dimension by reshaping
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [68]:
x_reshaped = x.reshape(1, 9)

In [69]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
# A view shares the same memory with the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [71]:
# stack on top of each other, based on different dimension
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [73]:
# Squeeze and unsqueeze
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [74]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [75]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [76]:
x_reshaped.shape

torch.Size([1, 9])

In [77]:
x_reshaped.squeeze().shape

torch.Size([9])

In [78]:
# torch.unsqueeze() - adds a single dimension to a target tensor a specific dime
print(f"Prior target: {x_reshaped}")
print(f"Prior to unsqueeze: {x_reshaped.shape}")

# add extra dimension
x_unsqueezed = x_reshaped.unsqueeze(dim=1)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


Prior target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Prior to unsqueeze: torch.Size([1, 9])
After unsqueeze: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [79]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


After unsqueeze: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [80]:
# Permute, rearrange dimension based on their dim order
# commonly seen when handling images

x_original = torch.rand(size=(224, 224, 3)) # (height, width, color channel)

# permute to get (color channel, height, width)
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0
x_permuted.shape


torch.Size([3, 224, 224])

## Indexing

Indexing with PyTorch is similar to NumPy

In [81]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [82]:

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [83]:
x[0][0]

tensor([1, 2, 3])

In [84]:
x[0, 0]

tensor([1, 2, 3])

In [85]:
x[0][0][0]

tensor(1)

In [86]:
# use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [87]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [88]:
# get all values in 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]
# equals to x[0][1][1] or x[0, 1, 1]

tensor([5])

In [89]:
# get index 0 of 0th and 1st dim, and all value of 2nd dim
x[0, 0, :]
# equals to x[0][0]

tensor([1, 2, 3])

In [90]:
# index to get the value 9
x[0, 2, 2]

tensor(9)

In [91]:
# index to get [3, 6, 9]
x[0, :, 2]

tensor([3, 6, 9])

In [92]:
# Index on x to return 9
print(x[0][2][2])

print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and Numpy
* numpy -> PyTorch : `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy : `torch.Tensor.numpy()`

In [93]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
# numpy default data type is float 64, where pytorch default is float 32
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [95]:
# we can specify data type in preparation of pytorch tensor use
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [96]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [97]:
# changing the value of array, tensor that was created from it won't be affected
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [98]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

# the numpy created from tensor will have tensor data type
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [99]:
# Change the tensor, the numpy array created from it won't be affected
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
To reduce randomness in NN and PyTorch comes from **random seed**.

In [100]:
torch.rand(3, 3)

tensor([[0.2249, 0.3634, 0.2126],
        [0.7516, 0.6146, 0.1972],
        [0.4732, 0.7314, 0.4242]])

In [101]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6748, 0.8254, 0.2007, 0.9034],
        [0.5918, 0.3338, 0.3328, 0.8911],
        [0.4115, 0.2685, 0.5496, 0.3815]])
tensor([[0.9106, 0.3903, 0.0258, 0.8971],
        [0.2831, 0.7027, 0.8183, 0.5264],
        [0.6302, 0.2670, 0.4315, 0.8278]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [102]:
# Let's make random but reproducible tensors, by setting random seed

import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# manual seed needs to be set after a call if you want the next random call to
# use the same random init values
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPU
- Free, on demand, pay for usage services like google colab
- Cloud service like aws, gcp, alibaba
- Build your own machine, with graphic cards and other hardware

In [103]:
!nvidia-smi

Sun May 25 20:19:32 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P0             27W /   70W |     120MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for gpu access with PyTorch

In [104]:
import torch

torch.cuda.is_available()

True

In [105]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [106]:
# We can also COUNT number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on GPUs

In [107]:
# create a tensor (default on cpu)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [108]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

## 4. Moving tensors back to CPU


In [109]:
# If tensor is on GPU, can't transform it to numpy, need to move it to cpu first

#tensor_on_gpu.numpy()

In [110]:
# to fix the GPU tensor with numpy issue, set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### So in summary, use `!nvidia-smi` for general info, use device with `torch.cuda.is_available()` to set hardware agnostic device, and move back to cpu if needing numpy.