<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.type()

'torch.LongTensor'

In [5]:
scalar.ndim
# scala has zero or no dimension

0

In [6]:
scalar.item()
# only works with one-element tensors

7

In [7]:
type(scalar.item())
# returns a python type int

int

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [12]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [15]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
tensor.device

device(type='cpu')

In [20]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9508, 0.8840, 0.5307, 0.3568],
        [0.7019, 0.5271, 0.8033, 0.3889],
        [0.4568, 0.0218, 0.9432, 0.4994]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.5411, 0.9434, 0.3437, 0.7307, 0.2469, 0.9731, 0.2738, 0.2438,
          0.7392, 0.3203],
         [0.5359, 0.5637, 0.4711, 0.4335, 0.9573, 0.1267, 0.2579, 0.1750,
          0.1604, 0.0698],
         [0.9743, 0.0053, 0.5742, 0.1633, 0.1108, 0.3752, 0.6135, 0.5467,
          0.9028, 0.8515],
         [0.4410, 0.7042, 0.2179, 0.7681, 0.3131, 0.1633, 0.3390, 0.2381,
          0.0916, 0.9586],
         [0.7666, 0.9345, 0.5421, 0.7689, 0.6560, 0.5970, 0.9614, 0.3729,
          0.4720, 0.8481],
         [0.8182, 0.6655, 0.0647, 0.9299, 0.7384, 0.6859, 0.5133, 0.1527,
          0.5130, 0.5632],
         [0.5940, 0.0316, 0.7853, 0.8834, 0.9630, 0.0509, 0.8631, 0.3206,
          0.9802, 0.3301],
         [0.7088, 0.8290, 0.1430, 0.5936, 0.6425, 0.5470, 0.6745, 0.9249,
          0.5323, 0.2635],
         [0.2877, 0.3344, 0.6820, 0.8840, 0.1322, 0.5887, 0.4930, 0.8604,
          0.1933, 0.9867],
         [0.1420, 0.7967, 0.5087, 0.9565, 0.8315, 0.0577, 0.6013, 0.9327,
          0.4264,

In [24]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [27]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [30]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
** Notes: ** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensor not the right datatype
2. Tensor not the right shape
3. Tensor not on the right device

In [31]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [32]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data types, float32 or float16, etc
                               device=device, # what device is the tensor on, cpu or cuda
                               requires_grad=False # should track gradients
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [33]:
# dtype of a tensor is default to float32, even if we specified it to None
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.half)
# half is same as float16, and float_16 apparently takes other attributes like device from float_32
float_16_tensor, float_16_tensor.device, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16),
 device(type='cuda', index=0),
 torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting information from tensors
* `shape` what shape is the tensor (some operations require specific shape rule)
* `dtype` what data type are stored in the tensor
* `device` what device the tensor is on (usually GPU or CPU)


In [36]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find some details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8891, 0.4114, 0.3820, 0.7003],
        [0.9940, 0.7705, 0.2483, 0.3060],
        [0.8075, 0.3270, 0.3890, 0.9725]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

In [37]:
# create tensor and add numbers to elements
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [38]:
tensor + 10

tensor([11, 12, 13])

In [39]:
# multiply elements
tensor * 10

tensor([10, 20, 30])

In [40]:
# tensor doesn't change unless reassigned
tensor

tensor([1, 2, 3])

### Matrix multiplication (is all you need)
The most common operation in neural net and deep learning is `matrix multiplication`, aka matmul in PyTorch.

The two rules for mat mul is:
1) The **inner dimensions** must match
2) The resulting matrix has the **outer dimensions**

In [41]:
# element wise multi
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# the at @ symbol is an operator for matmul
tensor @ tensor

tensor(14)

In [44]:
# so is torch.mm
# BUT torch.mm only works with matrix, not vector or tensor

# torch.mm(tensor, tensor)


In [45]:
%%time

# mat mul with loops
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 647 µs, sys: 0 ns, total: 647 µs
Wall time: 2.6 ms


In [46]:
%%time

# mat mul with torch method, which is faster by 3 order of magnitude
torch.matmul(tensor, tensor)

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 36 µs


tensor(14)

### The most common in deep learning: shape errors   
To fix tensor shape issue, we can manipulate the shape of tensor using transpose


In [47]:
# create two tensor
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [48]:
# use T, or transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [49]:
# with b transposed, now the rule for mat mul is met
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum and other tensor aggregation.

In [50]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
# find avg

# watch out for dtype error for the dtype error
#torch.mean(x), x.mean()


In [54]:
# Need to specify data type from int/long to some float so we can do mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding position min and max, aka argmin and argmax

In [56]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# argmin
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [58]:
# argmax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [59]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

* **Reshaping** - change shape of input tensor to a defined shape. _Total element counts need to be the same before and after._
* **View** - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* **Stacking** - combine multiple tensors on top of each other `vstack` or side by side `hstack`
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a tensor
* **Permute** - return a *view* of input with dimension order swapped in certain way

In [60]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# add an extra dimension by reshaping
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
x_reshaped = x.reshape(1, 9)

In [64]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# A view shares the same memory with the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# stack on top of each other, based on different dimension
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [68]:
# Squeeze and unsqueeze
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [69]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [70]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [71]:
x_reshaped.shape

torch.Size([1, 9])

In [72]:
x_reshaped.squeeze().shape

torch.Size([9])

In [73]:
# torch.unsqueeze() - adds a single dimension to a target tensor a specific dime
print(f"Prior target: {x_reshaped}")
print(f"Prior to unsqueeze: {x_reshaped.shape}")

# add extra dimension
x_unsqueezed = x_reshaped.unsqueeze(dim=1)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


Prior target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Prior to unsqueeze: torch.Size([1, 9])
After unsqueeze: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [74]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


After unsqueeze: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [75]:
# Permute, rearrange dimension based on their dim order
# commonly seen when handling images

x_original = torch.rand(size=(224, 224, 3)) # (height, width, color channel)

# permute to get (color channel, height, width)
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0
x_permuted.shape


torch.Size([3, 224, 224])

## Indexing

Indexing with PyTorch is similar to NumPy

In [76]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
x[0][0]

tensor([1, 2, 3])

In [79]:
x[0, 0]

tensor([1, 2, 3])

In [80]:
x[0][0][0]

tensor(1)

In [81]:
# use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [83]:
# get all values in 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]
# equals to x[0][1][1] or x[0, 1, 1]

tensor([5])

In [84]:
# get index 0 of 0th and 1st dim, and all value of 2nd dim
x[0, 0, :]
# equals to x[0][0]

tensor([1, 2, 3])

In [85]:
# index to get the value 9
x[0, 2, 2]

tensor(9)

In [86]:
# index to get [3, 6, 9]
x[0, :, 2]

tensor([3, 6, 9])

In [87]:
# Index on x to return 9
print(x[0][2][2])

print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and Numpy
* numpy -> PyTorch : `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy : `torch.Tensor.numpy()`

In [88]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
# numpy default data type is float 64, where pytorch default is float 32
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [90]:
# we can specify data type in preparation of pytorch tensor use
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [91]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [92]:
# changing the value of array, tensor that was created from it won't be affected
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [93]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

# the numpy created from tensor will have tensor data type
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
# Change the tensor, the numpy array created from it won't be affected
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))