<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [35]:
scalar = torch.tensor(7)

In [36]:
scalar

tensor(7)

In [37]:
scalar.type()

'torch.LongTensor'

In [38]:
scalar.ndim
# scala has zero or no dimension

0

In [39]:
scalar.item()
# only works with one-element tensors

7

In [40]:
type(scalar.item())
# returns a python type int

int

In [41]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [42]:
vector.ndim

1

In [43]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [44]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [45]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [46]:
matrix.ndim

2

In [47]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [48]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [49]:
tensor.ndim

3

In [50]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [51]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [52]:
tensor.device

device(type='cpu')

In [53]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [54]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[5.2500e-02, 4.9422e-01, 2.7648e-01, 8.7330e-01],
        [7.4775e-01, 4.0549e-01, 6.8031e-01, 7.1977e-01],
        [7.7161e-01, 2.2805e-04, 7.3878e-01, 8.6416e-01]])

In [55]:
random_tensor.ndim

2

In [56]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.7687, 0.6395, 0.4257, 0.7286, 0.2681, 0.0789, 0.7162, 0.1352,
          0.0958, 0.3727],
         [0.9885, 0.5620, 0.3998, 0.3710, 0.1310, 0.0277, 0.7800, 0.3764,
          0.4863, 0.1009],
         [0.2684, 0.7473, 0.3874, 0.9592, 0.2862, 0.9626, 0.1506, 0.5070,
          0.0585, 0.9687],
         [0.8080, 0.3934, 0.7323, 0.8894, 0.0212, 0.4714, 0.4713, 0.9844,
          0.2217, 0.5170],
         [0.8873, 0.6818, 0.9799, 0.5515, 0.2009, 0.4952, 0.2158, 0.4120,
          0.0185, 0.2980],
         [0.5737, 0.8434, 0.4406, 0.0475, 0.0665, 0.3751, 0.4371, 0.2239,
          0.6900, 0.5726],
         [0.3704, 0.5112, 0.9042, 0.7196, 0.1615, 0.2166, 0.9779, 0.2708,
          0.7329, 0.4358],
         [0.8762, 0.1413, 0.5702, 0.3073, 0.5915, 0.7120, 0.6911, 0.1344,
          0.3306, 0.9646],
         [0.3977, 0.0563, 0.6301, 0.8813, 0.1752, 0.5342, 0.8492, 0.3694,
          0.4118, 0.2316],
         [0.6816, 0.2356, 0.6540, 0.6112, 0.6370, 0.1302, 0.7879, 0.9878,
          0.8194,

In [57]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [58]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [60]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [62]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [63]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
** Notes: ** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensor not the right datatype
2. Tensor not the right shape
3. Tensor not on the right device

In [64]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [65]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data types, float32 or float16, etc
                               device=device, # what device is the tensor on, cpu or cuda
                               requires_grad=False # should track gradients
                               )
float_32_tensor

tensor([3., 6., 9.])

In [66]:
# dtype of a tensor is default to float32, even if we specified it to None
float_32_tensor.dtype

torch.float32

In [67]:
float_16_tensor = float_32_tensor.type(torch.half)
# half is same as float16, and float_16 apparently takes other attributes like device from float_32
float_16_tensor, float_16_tensor.device, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), device(type='cpu'), torch.float16)

In [68]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
* `shape` what shape is the tensor (some operations require specific shape rule)
* `dtype` what data type are stored in the tensor
* `device` what device the tensor is on (usually GPU or CPU)


In [69]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find some details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4871, 0.9973, 0.4729, 0.3396],
        [0.4438, 0.4629, 0.8664, 0.8654],
        [0.3595, 0.6091, 0.1460, 0.7931]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

In [70]:
# create tensor and add numbers to elements
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [71]:
tensor + 10

tensor([11, 12, 13])

In [72]:
# multiply elements
tensor * 10

tensor([10, 20, 30])

In [73]:
# tensor doesn't change unless reassigned
tensor

tensor([1, 2, 3])

### Matrix multiplication (is all you need)
The most common operation in neural net and deep learning is `matrix multiplication`, aka matmul in PyTorch.

The two rules for mat mul is:
1) The **inner dimensions** must match
2) The resulting matrix has the **outer dimensions**

In [74]:
# element wise multi
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [75]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [76]:
# the at @ symbol is an operator for matmul
tensor @ tensor

tensor(14)

In [77]:
# so is torch.mm
# BUT torch.mm only works with matrix, not vector or tensor

# torch.mm(tensor, tensor)


In [78]:
%%time

# mat mul with loops
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.31 ms, sys: 0 ns, total: 2.31 ms
Wall time: 2.26 ms


In [79]:
%%time

# mat mul with torch method, which is faster by 3 order of magnitude
torch.matmul(tensor, tensor)

CPU times: user 70 µs, sys: 10 µs, total: 80 µs
Wall time: 84.2 µs


tensor(14)

### The most common in deep learning: shape errors   
To fix tensor shape issue, we can manipulate the shape of tensor using transpose


In [80]:
# create two tensor
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [81]:
# use T, or transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [82]:
# with b transposed, now the rule for mat mul is met
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum and other tensor aggregation.

In [83]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [85]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [86]:
# find avg

# watch out for dtype error for the dtype error
#torch.mean(x), x.mean()


In [87]:
# Need to specify data type from int/long to some float so we can do mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [88]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding position min and max, aka argmin and argmax

In [89]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
# argmin
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [91]:
# argmax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [92]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

* **Reshaping** - change shape of input tensor to a defined shape. _Total element counts need to be the same before and after._
* **View** - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* **Stacking** - combine multiple tensors on top of each other `vstack` or side by side `hstack`
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a tensor
* **Permute** - return a *view* of input with dimension order swapped in certain way

In [112]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [113]:
# add an extra dimension by reshaping
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [114]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [115]:
x_reshaped = x.reshape(1, 9)

In [96]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [116]:
# A view shares the same memory with the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [117]:
# stack on top of each other, based on different dimension
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [119]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [120]:
# Squeeze and unsqueeze
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [121]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [122]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [123]:
x_reshaped.shape

torch.Size([1, 9])

In [124]:
x_reshaped.squeeze().shape

torch.Size([9])

In [126]:
# torch.unsqueeze() - adds a single dimension to a target tensor a specific dime
print(f"Prior target: {x_reshaped}")
print(f"Prior to unsqueeze: {x_reshaped.shape}")

# add extra dimension
x_unsqueezed = x_reshaped.unsqueeze(dim=1)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


Prior target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Prior to unsqueeze: torch.Size([1, 9])
After unsqueeze: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [127]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


After unsqueeze: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [129]:
# Permute, rearrange dimension based on their dim order
# commonly seen when handling images

x_original = torch.rand(size=(224, 224, 3)) # (height, width, color channel)

# permute to get (color channel, height, width)
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0
x_permuted.shape


torch.Size([3, 224, 224])

## Indexing

Indexing with PyTorch is similar to NumPy

In [131]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [133]:

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [132]:
x[0][0]

tensor([1, 2, 3])

In [134]:
x[0, 0]

tensor([1, 2, 3])

In [135]:
x[0][0][0]

tensor(1)

In [142]:
# use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [144]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [148]:
# get all values in 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]
# equals to x[0][1][1] or x[0, 1, 1]

tensor([5])

In [146]:
# get index 0 of 0th and 1st dim, and all value of 2nd dim
x[0, 0, :]
# equals to x[0][0]

tensor([1, 2, 3])

In [149]:
# index to get the value 9
x[0, 2, 2]

tensor(9)

In [150]:
# index to get [3, 6, 9]
x[0, :, 2]

tensor([3, 6, 9])