<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.type()

'torch.LongTensor'

In [5]:
scalar.ndim
# scala has zero or no dimension

0

In [6]:
scalar.item()
# only works with one-element tensors

7

In [7]:
type(scalar.item())
# returns a python type int

int

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [12]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [15]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
tensor.device

device(type='cpu')

In [20]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2538, 0.6669, 0.3703, 0.7765],
        [0.5339, 0.1972, 0.7531, 0.5998],
        [0.1957, 0.2591, 0.8431, 0.1184]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.0267, 0.7840, 0.7641, 0.2636, 0.8727, 0.4979, 0.1235, 0.9208,
          0.5053, 0.6924],
         [0.1592, 0.8050, 0.3626, 0.1143, 0.1228, 0.1505, 0.6102, 0.3894,
          0.0909, 0.7755],
         [0.1076, 0.9406, 0.5109, 0.6712, 0.5889, 0.6146, 0.0242, 0.4140,
          0.7703, 0.7138],
         [0.6398, 0.3590, 0.0826, 0.1593, 0.6241, 0.9976, 0.3354, 0.6227,
          0.7886, 0.4550],
         [0.3690, 0.0394, 0.6664, 0.0240, 0.0417, 0.4868, 0.8208, 0.9441,
          0.1684, 0.3058],
         [0.1822, 0.9494, 0.5236, 0.9864, 0.9540, 0.3198, 0.7251, 0.3525,
          0.3214, 0.7911],
         [0.2095, 0.2891, 0.2925, 0.5698, 0.4913, 0.1306, 0.0891, 0.7392,
          0.1445, 0.0240],
         [0.7897, 0.5994, 0.7010, 0.2541, 0.8614, 0.9000, 0.9303, 0.8501,
          0.0544, 0.2512],
         [0.1185, 0.0496, 0.4949, 0.3670, 0.1995, 0.0104, 0.0951, 0.4671,
          0.4380, 0.3230],
         [0.1972, 0.8926, 0.7550, 0.6206, 0.0416, 0.2910, 0.3598, 0.7690,
          0.0956,

In [24]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [27]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [30]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
** Notes: ** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensor not the right datatype
2. Tensor not the right shape
3. Tensor not on the right device

In [31]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [32]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data types, float32 or float16, etc
                               device=device, # what device is the tensor on, cpu or cuda
                               requires_grad=False # should track gradients
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [33]:
# dtype of a tensor is default to float32, even if we specified it to None
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.half)
# half is same as float16, and float_16 apparently takes other attributes like device from float_32
float_16_tensor, float_16_tensor.device, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16),
 device(type='cuda', index=0),
 torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting information from tensors
* `shape` what shape is the tensor (some operations require specific shape rule)
* `dtype` what data type are stored in the tensor
* `device` what device the tensor is on (usually GPU or CPU)


In [36]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find some details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2780, 0.6474, 0.0336, 0.2397],
        [0.1479, 0.4736, 0.8169, 0.9709],
        [0.0139, 0.2512, 0.7638, 0.6693]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

In [37]:
# create tensor and add numbers to elements
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [38]:
tensor + 10

tensor([11, 12, 13])

In [39]:
# multiply elements
tensor * 10

tensor([10, 20, 30])

In [40]:
# tensor doesn't change unless reassigned
tensor

tensor([1, 2, 3])

### Matrix multiplication (is all you need)
The most common operation in neural net and deep learning is `matrix multiplication`, aka matmul in PyTorch.

The two rules for mat mul is:
1) The **inner dimensions** must match
2) The resulting matrix has the **outer dimensions**

In [41]:
# element wise multi
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# the at @ symbol is an operator for matmul
tensor @ tensor

tensor(14)

In [44]:
# so is torch.mm
# BUT torch.mm only works with matrix, not vector or tensor

# torch.mm(tensor, tensor)


In [45]:
%%time

# mat mul with loops
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.4 ms, sys: 0 ns, total: 1.4 ms
Wall time: 6.9 ms


In [46]:
%%time

# mat mul with torch method, which is faster by 3 order of magnitude
torch.matmul(tensor, tensor)

CPU times: user 42 µs, sys: 10 µs, total: 52 µs
Wall time: 54.6 µs


tensor(14)

### The most common in deep learning: shape errors   
To fix tensor shape issue, we can manipulate the shape of tensor using transpose


In [47]:
# create two tensor
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [48]:
# use T, or transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [49]:
# with b transposed, now the rule for mat mul is met
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum and other tensor aggregation.

In [50]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
# find avg

# watch out for dtype error for the dtype error
#torch.mean(x), x.mean()


In [54]:
# Need to specify data type from int/long to some float so we can do mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding position min and max, aka argmin and argmax

In [56]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# argmin
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [58]:
# argmax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [59]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

* **Reshaping** - change shape of input tensor to a defined shape. _Total element counts need to be the same before and after._
* **View** - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* **Stacking** - combine multiple tensors on top of each other `vstack` or side by side `hstack`
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a tensor
* **Permute** - return a *view* of input with dimension order swapped in certain way

In [60]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# add an extra dimension by reshaping
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
x_reshaped = x.reshape(1, 9)

In [64]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# A view shares the same memory with the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# stack on top of each other, based on different dimension
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [68]:
# Squeeze and unsqueeze
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [69]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [70]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [71]:
x_reshaped.shape

torch.Size([1, 9])

In [72]:
x_reshaped.squeeze().shape

torch.Size([9])

In [73]:
# torch.unsqueeze() - adds a single dimension to a target tensor a specific dime
print(f"Prior target: {x_reshaped}")
print(f"Prior to unsqueeze: {x_reshaped.shape}")

# add extra dimension
x_unsqueezed = x_reshaped.unsqueeze(dim=1)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


Prior target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Prior to unsqueeze: torch.Size([1, 9])
After unsqueeze: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [74]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(f"After unsqueeze: {x_unsqueezed}")
print(f"After unsqueeze: {x_unsqueezed.shape}")


After unsqueeze: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
After unsqueeze: torch.Size([1, 1, 9])


In [75]:
# Permute, rearrange dimension based on their dim order
# commonly seen when handling images

x_original = torch.rand(size=(224, 224, 3)) # (height, width, color channel)

# permute to get (color channel, height, width)
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0
x_permuted.shape


torch.Size([3, 224, 224])

## Indexing

Indexing with PyTorch is similar to NumPy

In [76]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
x[0][0]

tensor([1, 2, 3])

In [79]:
x[0, 0]

tensor([1, 2, 3])

In [80]:
x[0][0][0]

tensor(1)

In [81]:
# use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [83]:
# get all values in 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]
# equals to x[0][1][1] or x[0, 1, 1]

tensor([5])

In [84]:
# get index 0 of 0th and 1st dim, and all value of 2nd dim
x[0, 0, :]
# equals to x[0][0]

tensor([1, 2, 3])

In [85]:
# index to get the value 9
x[0, 2, 2]

tensor(9)

In [86]:
# index to get [3, 6, 9]
x[0, :, 2]

tensor([3, 6, 9])

In [87]:
# Index on x to return 9
print(x[0][2][2])

print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and Numpy
* numpy -> PyTorch : `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy : `torch.Tensor.numpy()`

In [88]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
# numpy default data type is float 64, where pytorch default is float 32
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [90]:
# we can specify data type in preparation of pytorch tensor use
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [91]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [92]:
# changing the value of array, tensor that was created from it won't be affected
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [93]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

# the numpy created from tensor will have tensor data type
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
# Change the tensor, the numpy array created from it won't be affected
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
To reduce randomness in NN and PyTorch comes from **random seed**.

In [95]:
torch.rand(3, 3)

tensor([[0.2909, 0.8783, 0.0979],
        [0.3629, 0.3878, 0.3196],
        [0.5949, 0.4060, 0.4517]])

In [96]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4867, 0.2292, 0.8789, 0.5767],
        [0.6741, 0.8025, 0.7131, 0.5689],
        [0.4465, 0.2853, 0.4074, 0.4335]])
tensor([[0.3192, 0.1923, 0.9880, 0.7044],
        [0.4516, 0.2214, 0.0759, 0.2088],
        [0.4098, 0.7389, 0.4125, 0.1323]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# Let's make random but reproducible tensors, by setting random seed

import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# manual seed needs to be set after a call if you want the next random call to
# use the same random init values
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
