<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/pytorch_toturial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.type()

'torch.LongTensor'

In [5]:
scalar.ndim
# scala has zero or no dimension

0

In [6]:
scalar.item()
# only works with one-element tensors

7

In [7]:
type(scalar.item())
# returns a python type int

int

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [12]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [15]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
tensor.device

device(type='cpu')

In [20]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6025, 0.4036, 0.4148, 0.2168],
        [0.8498, 0.6637, 0.2659, 0.7574],
        [0.1057, 0.9012, 0.3978, 0.1597]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.2644, 0.9544, 0.2314, 0.3845, 0.9544, 0.9024, 0.1730, 0.7996,
          0.5636, 0.1078],
         [0.4367, 0.4729, 0.7988, 0.7361, 0.2779, 0.7409, 0.3824, 0.2993,
          0.3936, 0.7895],
         [0.0859, 0.2163, 0.0787, 0.2684, 0.4933, 0.3207, 0.0528, 0.3202,
          0.6171, 0.9359],
         [0.3593, 0.8357, 0.5697, 0.1849, 0.3420, 0.1094, 0.2178, 0.2896,
          0.8198, 0.4816],
         [0.3832, 0.2894, 0.8199, 0.4171, 0.3385, 0.6604, 0.6915, 0.1124,
          0.3518, 0.9004],
         [0.8406, 0.5099, 0.3979, 0.8999, 0.5300, 0.6758, 0.5216, 0.6055,
          0.3488, 0.5166],
         [0.4093, 0.3464, 0.1515, 0.9151, 0.2328, 0.6529, 0.5899, 0.3368,
          0.3767, 0.7156],
         [0.3806, 0.5044, 0.3168, 0.9104, 0.9764, 0.3047, 0.7565, 0.3119,
          0.7468, 0.8757],
         [0.9325, 0.0118, 0.3838, 0.4208, 0.1567, 0.1496, 0.8601, 0.9905,
          0.0242, 0.3109],
         [0.3172, 0.9729, 0.9291, 0.8574, 0.5498, 0.4814, 0.2344, 0.2029,
          0.5906,

In [24]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [27]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [30]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
** Notes: ** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensor not the right datatype
2. Tensor not the right shape
3. Tensor not on the right device

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data types, float32 or float16, etc
                               device='cuda', # what device is the tensor on, cpu or cuda
                               requires_grad=False # should track gradients
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [32]:
# dtype of a tensor is default to float32, even if we specified it to None
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.half)
# half is same as float16, and float_16 apparently takes other attributes like device from float_32
float_16_tensor, float_16_tensor.device, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16),
 device(type='cuda', index=0),
 torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting information from tensors
* `shape` what shape is the tensor (some operations require specific shape rule)
* `dtype` what data type are stored in the tensor
* `device` what device the tensor is on (usually GPU or CPU)


In [35]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find some details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9444, 0.1662, 0.2845, 0.9194],
        [0.8003, 0.2277, 0.8955, 0.6723],
        [0.9595, 0.9595, 0.3638, 0.8338]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

In [37]:
# create tensor and add numbers to elements
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [38]:
tensor + 10

tensor([11, 12, 13])

In [39]:
# multiply elements
tensor * 10

tensor([10, 20, 30])

In [40]:
# tensor doesn't change unless reassigned
tensor

tensor([1, 2, 3])

### Matrix multiplication (is all you need)
The most common operation in neural net and deep learning is `matrix multiplication`, aka dot product, aka matmul in PyTorch.

The two rules for mat mul is:
1) The **inner dimensions** must match
2) The resulting matrix has the **outer dimensions**