<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/pytorch_toturial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [3]:
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.type()

'torch.LongTensor'

In [6]:
scalar.ndim
# scala has zero or no dimension

0

In [7]:
scalar.item()
# only works with one-element tensors

7

In [8]:
type(scalar.item())
# returns a python type int

int

In [9]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [12]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [13]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [16]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.ndim

3

In [18]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [19]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [20]:
tensor.device

device(type='cpu')

In [21]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [22]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4008, 0.0425, 0.3959, 0.4912],
        [0.4688, 0.5235, 0.1998, 0.5929],
        [0.2269, 0.1241, 0.4124, 0.5154]])

In [23]:
random_tensor.ndim

2

In [25]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.7952, 0.1073, 0.4923, 0.7426, 0.4763, 0.9304, 0.2109, 0.3062,
          0.1758, 0.9586],
         [0.4067, 0.5746, 0.1223, 0.3594, 0.9670, 0.9391, 0.2948, 0.5038,
          0.2754, 0.6413],
         [0.5690, 0.6348, 0.6447, 0.6210, 0.0464, 0.0298, 0.2204, 0.1392,
          0.8213, 0.2189],
         [0.6948, 0.4210, 0.3680, 0.3694, 0.0168, 0.8395, 0.0532, 0.0599,
          0.6695, 0.5480],
         [0.6838, 0.8492, 0.3883, 0.2053, 0.2838, 0.1728, 0.2948, 0.9300,
          0.5860, 0.3675],
         [0.8595, 0.1472, 0.6113, 0.2486, 0.2051, 0.5687, 0.5313, 0.7494,
          0.7329, 0.0664],
         [0.3738, 0.8456, 0.5971, 0.4588, 0.4682, 0.5109, 0.5005, 0.3862,
          0.8098, 0.9026],
         [0.9039, 0.7784, 0.0031, 0.2797, 0.8216, 0.8022, 0.7866, 0.0821,
          0.0582, 0.7175],
         [0.0945, 0.7587, 0.7527, 0.6200, 0.0256, 0.4185, 0.3266, 0.7633,
          0.5133, 0.1194],
         [0.2444, 0.0217, 0.4454, 0.0958, 0.0822, 0.0436, 0.6584, 0.9920,
          0.2225,

In [26]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [27]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [29]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [31]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [32]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])