<a href="https://colab.research.google.com/github/nlscng/turbo-doodle/blob/main/pytorch_toturial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.1+cu124'

### Introduction to tensors
Creating tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.type()

'torch.LongTensor'

In [5]:
scalar.ndim
# scala has zero or no dimension

0

In [6]:
scalar.item()
# only works with one-element tensors

7

In [7]:
type(scalar.item())
# returns a python type int

int

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape
# prints with torch.size?

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])

In [12]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

Creating tensors

In [15]:
# tensors
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape
# the first dim is 1, not 3

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
tensor.device

device(type='cpu')

In [20]:
tensor.dtype

torch.int64

### Random tensors
Why random tensors?
Random tensors are important because many NN start with random numbers for initial states

# Create a random tensor of size/shape (3, 4)

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9233, 0.0744, 0.3964, 0.6483],
        [0.1037, 0.5999, 0.8461, 0.8494],
        [0.6559, 0.2646, 0.1280, 0.5152]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.5232, 0.9757, 0.8911, 0.0328, 0.9881, 0.4551, 0.8272, 0.4234,
          0.0318, 0.5801],
         [0.5614, 0.8027, 0.8956, 0.6471, 0.5222, 0.0343, 0.5277, 0.4213,
          0.6354, 0.8293],
         [0.1766, 0.6245, 0.3972, 0.8436, 0.8351, 0.2940, 0.7926, 0.7183,
          0.0982, 0.8774],
         [0.1202, 0.1336, 0.9872, 0.7145, 0.7632, 0.3197, 0.4719, 0.9494,
          0.6579, 0.8505],
         [0.5975, 0.6493, 0.1942, 0.8201, 0.9660, 0.5935, 0.5209, 0.0725,
          0.7045, 0.8220],
         [0.6998, 0.2018, 0.6227, 0.0382, 0.1537, 0.2420, 0.8359, 0.5477,
          0.9347, 0.7491],
         [0.8292, 0.6970, 0.9490, 0.9344, 0.9454, 0.6462, 0.6664, 0.5574,
          0.7565, 0.7443],
         [0.6143, 0.6381, 0.5737, 0.4293, 0.3513, 0.5626, 0.8300, 0.5725,
          0.4175, 0.8794],
         [0.0635, 0.2895, 0.3529, 0.8054, 0.3761, 0.0894, 0.1178, 0.1509,
          0.3996, 0.7374],
         [0.5106, 0.1430, 0.8916, 0.4718, 0.1244, 0.1341, 0.7089, 0.7254,
          0.0627,

In [24]:
random_tensor.dtype

torch.float32

# Creating tensors of zeros and ones

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating tensors with arange and like
With three args, start (inclusive), end (exclusive), and step

The _like method create tensors with same shapes

In [27]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [30]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
** Notes: ** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensor not the right datatype
2. Tensor not the right shape
3. Tensor not on the right device

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data types, float32 or float16, etc
                               device='cuda', # what device is the tensor on, cpu or cuda
                               requires_grad=False # should track gradients
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [32]:
# dtype of a tensor is default to float32, even if we specified it to None
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.half)
# half is same as float16, and float_16 apparently takes other attributes like device from float_32
float_16_tensor, float_16_tensor.device, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16),
 device(type='cuda', index=0),
 torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')